### ISSUE TITLE
Problem with cursor column and row highlight

### ISSUE THREAD

**Issue by maotora** [drzaal/vert-laiton#1]
Hello, Thank you for this colorscheme.

I loved it the moment i saw it.. Really a green fan here!

One thing tho, i don't get the nice blended background on cursorline and cursor column highlights as the ones i'm used to.

This minor feature is really great! Please add it.. :)

Ref: [vert-lation view](http://imgur.com/RSIcD0E)

[PaperColor view](http://imgur.com/x5XsTGR)

Please note the papercolor one i took a screenshot wide enough to show the cursorline and also the cursorrow is displayed but very dim.

**Comment by launchcg-ztonia** [comment]
Oh nice. Yea, I'll add it.

**Comment by drzaal** [comment]
Resolved via
a7dbe8a6532dda51600420e49b336cddd84f895f

**Comment by maotora** [comment]
Sweet..! Thanks!! :+1:
